// HouseholdRule.swift
// MyChores
//
// Created on 2025-05-17.
//

import Foundation
import FirebaseFirestore

/// Represents a rule or guideline within a household
struct HouseholdRule: Identifiable, Codable, Equatable {
    /// Unique identifier for the rule, auto-generated by Firestore
    @DocumentID var id: String?
    
    /// ID of the household this rule belongs to
var householdId: String
    
    /// The text content of the rule
    var ruleText: String
    
    /// ID of the user who created this rule
    var createdByUserId: String
    
    /// Timestamp of when the rule was created
    var createdAt: Date
    
    /// Timestamp of the last update to this rule (optional)
    var lastUpdatedAt: Date?
    
    /// Optional display order for manual sorting of rules
    var displayOrder: Int?
    
    /// Custom CodingKeys to match Firestore field names, if necessary (optional for now if names match)
    // enum CodingKeys: String, CodingKey {
    //     case id
    //     case householdId
    //     case ruleText
    //     case createdByUserId
    //     case createdAt
    //     case lastUpdatedAt
    //     case displayOrder
    // }

    // MARK: - Equatable
    static func == (lhs: HouseholdRule, rhs: HouseholdRule) -> Bool {
        return lhs.id == rhs.id &&
               lhs.householdId == rhs.householdId &&
               lhs.ruleText == rhs.ruleText &&
               lhs.createdByUserId == rhs.createdByUserId &&
               lhs.createdAt == rhs.createdAt &&
               lhs.lastUpdatedAt == rhs.lastUpdatedAt &&
               lhs.displayOrder == rhs.displayOrder
    }
}
